on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: number
        required: true
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64:
        required: false

jobs:
  build-test-commit:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      
      - name: Google Artifacts Registry Access
        run: | 
          if [ -n "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" ]; then
            echo "@zero65:registry=https://asia-south1-npm.pkg.dev/zero65/npm/" > ~/.npmrc
            mkdir -p ~/.config/gcloud
            echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > ~/.config/gcloud/application_default_credentials.json
            npm install -g google-artifactregistry-auth
            npx google-artifactregistry-auth
          fi
          
      - run: npm ci

      - run: npm run build
      
      - run: npm run test
      
      - name: Commit and Push
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "Zero65 Bot"
            git config user.email "google-cloud-build@zero65.in"
            git add .
            git commit -m "npm run build"
            git push
          fi
