on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        required: false
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}
  
      - name: Trigger Google Cloud Build
        uses: google-github-actions/cloud-build@v0
        with:
          project_id: "zero65-test"
          config: "cloudbuild.yaml"
