on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        required: false
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}

      - name: Google Artifacts Registry Access
        run: | 
          if [ -n "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" ]; then
            mkdir -p ~/.config/gcloud
            echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > ~/.config/gcloud/application_default_credentials.json
          fi

      - name: Run Google Cloud Build with Inline Config
        run: |
          gcloud builds submit --config - --project YOUR_PROJECT_ID <<EOF
          steps:
          - name: gcr.io/cloud-builders/npm
            args: ["install"]
          - name: gcr.io/cloud-builders/docker
            args: ["build", "-t", "gcr.io/zero65-test/my-app", "."]
          - name: gcr.io/cloud-builders/docker
            args: ["push", "gcr.io/zero65-test/my-app"]
          - name: gcr.io/google.com/cloudsdktool/cloud-sdk
            entrypoint: gcloud
            args: ["run", "deploy", "my-app", "--image", "gcr.io/zero65-test/my-app", "--platform", "managed", "--region", "us-central1"]
          timeout: 900s
          EOF
