on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        required: true
    secrets:
      GOOGLE_APPLICATION_CREDENTIALS_BASE64:
        required: false

jobs:
  list-and-commit:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.NODE_VERSION }}
      
      - name: Google Artifacts Registry Access
        run: | 
          if [ -n "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" ]; then
            echo "@zero65:registry=https://asia-south1-npm.pkg.dev/zero65/npm/" > ~/.npmrc
            mkdir -p ~/.config/gcloud
            echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 --decode > ~/.config/gcloud/application_default_credentials.json
            npm install -g google-artifactregistry-auth
            npx google-artifactregistry-auth
          fi
          
      - run: npm ci

      - run: npm run lint
